settings:
  title: 'VieCode Server Monitoring'
  url: 'https://status.viecode.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: support
    name: VieCode Support
    url: 'https://www.viecode.com/support/'
    method: GET
    expectStatus: 200
  - id: mail
    name: VieCode Mail Server
    url: 'https://mail.viecode.com/'
    method: GET
    expectStatus: 400
